name: Analyze
on:
  push:
    branches:
      - master
      - dev
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  run:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macOS-latest]
        php-versions: ['7.2', '7.3', '8.0']
    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}
    steps:
      - name: Enforce LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
      - name: Install dependencies
        run: composer install
      - name: Run PHPCS
        run: php vendor/bin/phpcs --standard=PSR2 --ignore="autoload.php,Connector.php,libs/*" src
      - name: Run PHPStan
        run: php vendor/bin/phpstan analyse -c .phpstan.neon -l 6 src
      - name: Run PHPUnit
        run: php vendor/bin/phpunit tests
